# Generated by Django 4.2 on 2023-05-03 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='create_data',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 19, 47, 5, 115465, tzinfo=datetime.timezone.utc)),
        ),
    ]
